name: matfixer
description: "An App to Troubleshoot and fix any MATLAB error"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  firebase_core: ^3.13.0
  flutter:
    sdk: flutter
  flutter_ai_toolkit: ^0.8.0
  go_router: ^15.1.1
  google_generative_ai: ^0.4.7
  shared_preferences: ^2.5.3
  split_view: ^3.2.1
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets: 
   - assets/
